name: GitHub Pages
on:
    push:
        branches:
            - main
    workflow_dispatch:
jobs:
    build-docs:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
            - name: Install pnpm
              run: npm i -g pnpm@10
            - name: Install
              run: pnpm i
            - name: Build
              run: pnpm build
            - name: Build docs
              run: pnpm doc src/testdata/infer.ts
            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@v4.4.1
              with:
                  branch: gh-pages
                  folder: docs
